"""empty message

Revision ID: d844ce77832a
Revises: 6db9a6052609
Create Date: 2023-05-12 00:41:35.204230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd844ce77832a'
down_revision = '6db9a6052609'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'running_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('running_time', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
