"""empty message

Revision ID: fc2c0fad5f59
Revises: 94d7dfbd3add
Create Date: 2023-05-10 20:41:17.095312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc2c0fad5f59'
down_revision = '94d7dfbd3add'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('description', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
